### ISSUE TITLE
现在好像不能正常使用了

### ISSUE THREAD

**Issue by xiangshaocheng** [hao14293/HDUWebLogin#2]
卡在step3了

**Comment by hao14293** [comment]
我测了一下是可以的，把你的报错贴一下吧。

**Comment by xiangshaocheng** [comment]
Step3: Loggin and resolve response.
Begin to send login info
Login info send successfully
Resolving login result
Cannot resolve login result. Maybe the srun response format is changed

**Comment by xiangshaocheng** [comment]
控制台：
Step3: Loggin and resolve response.
Begin to send login info
Login info send successfully
Resolving login result
Cannot resolve login result. Maybe the srun response format is changed

在always_online.py中
if __name__ == "__main__":
    username = input("Your account: ")
    password = getpass("Your password: ")
我改为了：
if __name__ == "__main__":
    username = "2010xxxx"
    password = "Mypassword"

**Comment by hao14293** [comment]
你好，我这边测试是一切正常的，请阅读README，检查环境是否正确。
